apiVersion: v1
kind: Pod
metadata:
  name: testvolume
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx-volume
          mountPath: /data
  volumes:
    - name: nginx-volume
      hostPath:
        path: /path/on/host
