apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-git-daemonset
  labels:
    app: example
    test: edit
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx-git-daemonset
        image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-git-pod
  labels:
    test: edited-again
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-git-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx-git-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-git-statefulset
spec:
  serviceName: "example"
  replicas: 5
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
