apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-git-daemonset
  labels:
    app: example
    test: edit
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx-git-daemonset
        image: nginx:latest
