apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-git-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx-git-container
        image: nginx:latest
        ports:
        - containerPort: 80
