version: '3'
services:
 large-app:
  image: alpine:latest
  volumes:
      - ../html:/home/html
      - nfs:/home/nfs
  tty: true
  stdin_open: true

volumes:
 nfs:
  driver: local
  driver_opts:
   type: 'nfs'
   device: '10.111.195.93:/volume/nfs/general'
   o: 'addr=10.111.195.93,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
