apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-cluster-role-binding
subjects:
- kind: User
  name: "john.doe@example.com"  # Replace with the actual username or identity
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: example-cluster-role  # Replace with the actual ClusterRole name
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-role-binding
subjects:
- kind: User
  name: "john.doe@example.com"  # Replace with the actual username or identity
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: example-role  # Replace with the actual Role name
  apiGroup: rbac.authorization.k8s.io
