apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-cluster-role-binding
subjects:
- kind: User
  name: "john.doe@example.com"  # Replace with the actual username or identity
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: example-cluster-role  # Replace with the actual ClusterRole name
  apiGroup: rbac.authorization.k8s.io
